<a href="https://colab.research.google.com/github/yasirarism/Klasifikasi-Data-Kelulusan-Mahasiswa-Dengan-Python/blob/main/Algoritma_Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Klasifikasi Dengan Algoritma Naive Bayes  
Nama: Yasir Aris Munandar  
NIM : 180103163  
Kelas : TI 18A3  

Praktikum Algoritma Naive Bayes

In [43]:
import pandas as pd
import numpy as np

data_training = pd.read_excel("https://github.com/yasirarism/Klasifikasi-Data-Kelulusan-Mahasiswa-Dengan-Python/raw/main/Data%20Kelulusan%20Mahasiswa_Data%20Training.xls")
data_training.head()

#Jenis Kelamin = (Perempuan = 1, Laki-Laki = 2)
#Status Mahasiswa = (Bekerja = 1, Mahasiswa = 2)
#Status Nikah = (Belum Menikah = 1, Menikah = 2)
#Status Kelulusan = (Tepat = 1, Terlambat = 2)

NAMA  JENIS_KELAMIN  ...  IPK   STATUS_KELULUSAN
0           ANIK WIDAYANTI              1  ...  3.07                 2
1  DWI HESTYNA PRIHASTANTY              1  ...  3.17                 2
2       MURYA ARIEF BASUKI              1  ...  3.54                 2
3            NANIK SUSANTI              1  ...  3.41                 2
4        RIFKA ISTIQFARINA              1  ...  3.09                 2

[5 rows x 15 columns]

In [ ]:
data_training.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 379 entries, 0 to 378
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   NAMA              379 non-null    object 
 1   JENIS_KELAMIN     379 non-null    int64  
 2   STATUS_MAHASISWA  379 non-null    int64  
 3   UMUR              379 non-null    int64  
 4   STATUS_NIKAH      379 non-null    int64  
 5   IPS_1             379 non-null    float64
 6   IPS_2             379 non-null    float64
 7   IPS_3             379 non-null    float64
 8   IPS_4             379 non-null    float64
 9   IPS_5             379 non-null    float64
 10  IPS_6             379 non-null    float64
 11  IPS_7             379 non-null    float64
 12  IPS_8             379 non-null    float64
 13  IPK               379 non-null    float64
 14  STATUS_KELULUSAN  379 non-null    int64  
dtypes: float64(9), int64(5), object(1)
memory usage: 44.5+ KB


In [ ]:
# Cek apakah ada deret yang kosong
data_training.empty

False

In [ ]:
data_training.size

5685

In [ ]:
# Variabel independen
x = data_training.drop(['STATUS_KELULUSAN','NAMA'], axis=1)
x.head()

JENIS_KELAMIN  STATUS_MAHASISWA  UMUR  ...  IPS_7  IPS_8  IPK 
0              1                 1    28  ...   3.03    0.0  3.07
1              1                 2    32  ...   3.25    0.0  3.17
2              1                 1    29  ...   3.73    0.0  3.54
3              1                 2    27  ...   3.46    0.0  3.41
4              1                 1    29  ...   3.08    0.0  3.09

[5 rows x 13 columns]

In [ ]:
# Variabel Dependen
y = data_training['STATUS_KELULUSAN']
y.head(11)

0     2
1     2
2     2
3     2
4     2
5     2
6     1
7     1
8     2
9     2
10    2
Name: STATUS_KELULUSAN, dtype: int64

In [ ]:
# Import fungsi train_test_split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.05)

In [ ]:
# Import Gaussian Naive Bayes Model
from sklearn.naive_bayes import GaussianNB

# Mengaktifkan fungsi klasifikasi Naive Bayes
modelnb = GaussianNB()

# Memasukkan data training pada naive bayes
nbtrain = modelnb.fit(x_train, y_train)
nbtrain.class_count_

array([202., 158.])

In [ ]:
# Menentukan hasil prediksi dari x_test
y_pred = nbtrain.predict(x_test)
y_pred

array([1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1])

In [47]:
np.array(y_test)

array([2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 1, 2, 1, 1, 1])

In [ ]:
# Menentukan probabilitas hasil prediksi
nbtrain.predict_proba(x_test)

array([[9.93588860e-01, 6.41113974e-03],
       [5.35950923e-13, 1.00000000e+00],
       [1.49778117e-05, 9.99985022e-01],
       [9.99740632e-01, 2.59367905e-04],
       [9.99767256e-01, 2.32743621e-04],
       [9.99999503e-01, 4.97141644e-07],
       [9.93370060e-01, 6.62993965e-03],
       [4.81469819e-05, 9.99951853e-01],
       [3.60079999e-08, 9.99999964e-01],
       [9.95614938e-01, 4.38506185e-03],
       [9.93597948e-01, 6.40205211e-03],
       [9.99482293e-01, 5.17706500e-04],
       [9.99787415e-01, 2.12584684e-04],
       [3.26674720e-01, 6.73325280e-01],
       [9.82579183e-01, 1.74208173e-02],
       [2.68090612e-04, 9.99731909e-01],
       [9.99568624e-01, 4.31375909e-04],
       [9.51206917e-01, 4.87930835e-02],
       [9.99835218e-01, 1.64782405e-04]])

In [ ]:
# Import confusion matrix model
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[12,  2],
       [ 1,  4]])

In [48]:
# Merapikan hasil confusion matrix
y_actual1 = pd.Series([2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 1, 2, 1, 1, 1], name="actual")
y_pred1 = pd.Series([1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1], name="prediction")
df_confusion = pd.crosstab(y_actual1, y_pred1)
df_confusion

prediction  1  2
actual          
1           9  0
2           4  6

In [44]:
# Menghitung nilai akurasi klasifikasi naive bayes
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.69      1.00      0.82         9
           2       1.00      0.60      0.75        10

    accuracy                           0.79        19
   macro avg       0.85      0.80      0.78        19
weighted avg       0.85      0.79      0.78        19

